
spring:
  application:
    name: home-manager
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      jdbc:
       time_zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER_NAME}
    password: ${PG_PASS}
    url: jdbc:postgresql://localhost:5432/homeManager
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss

logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG